import "@/assets/css/global.css";
import { Inter } from "next/font/google";
import ThemeProviderComp from "@/components/ThemeProviderComp";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProviderComp>
        <body className={inter.className}>{children}</body>
      </ThemeProviderComp>
    </html>
  );
}
